# Generated by Django 2.1.7 on 2020-11-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='import_check_list',
            name='tip_no',
            field=models.IntegerField(default=0),
        ),
    ]
