# Generated by Django 2.1.7 on 2020-11-09 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tooling_form', '0002_import_check_list_tip_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlm_info',
            name='no',
        ),
        migrations.RemoveField(
            model_name='mlm_info_temp',
            name='no',
        ),
    ]
