# Generated by Django 2.1.7 on 2020-11-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling_form', '0003_auto_20201109_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_check_list',
            name='tip_no',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='import_error_list',
            name='tip_no',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='import_list',
            name='tip_no',
            field=models.CharField(max_length=9),
        ),
    ]
