# Generated by Django 2.1.7 on 2020-11-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling_form', '0004_auto_20201109_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='column',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='setting',
            name='row',
            field=models.IntegerField(default=0),
        ),
    ]
