# Generated by Django 2.1.7 on 2020-11-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tooling_form', '0005_auto_20201109_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='import_list',
            old_name='ole_file_name',
            new_name='old_file_name',
        ),
    ]
