# Generated by Django 2.1.7 on 2020-11-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling_form', '0006_auto_20201110_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='import_check_list',
            name='error_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
