# Generated by Django 2.1.7 on 2020-11-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tooling_form', '0007_import_check_list_error_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='import_check_list',
            old_name='error_code',
            new_name='check_code',
        ),
    ]
