# Generated by Django 2.1.7 on 2020-11-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling_form', '0009_auto_20201111_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='enable',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='regex',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='setting',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
