# Generated by Django 2.1.7 on 2020-11-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling_form', '0010_auto_20201111_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_info',
            name='mask_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
