# Generated by Django 2.1.7 on 2020-12-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling_form', '0011_device_info_mask_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapeout_info',
            name='no',
            field=models.IntegerField(null=True),
        ),
    ]
