# Generated by Django 2.1.7 on 2019-12-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20191223_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
