# Generated by Django 2.1.7 on 2019-12-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20191223_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_date',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='update_date',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='user',
            name='update_time',
            field=models.IntegerField(default=0),
        ),
    ]
