# Generated by Django 2.1.7 on 2019-12-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20191230_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.CharField(default='', max_length=45)),
                ('create_time', models.IntegerField(default=0)),
                ('update_time', models.IntegerField(default=0)),
                ('update_date', models.CharField(default='', max_length=45)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256)),
                ('update_by', models.CharField(default='', max_length=256)),
                ('value', models.CharField(default='', max_length=256)),
                ('type', models.CharField(default='', max_length=256)),
                ('description', models.CharField(default='', max_length=256, null=True)),
                ('sort', models.IntegerField(default=0)),
                ('parent_id', models.CharField(default='', max_length=256, null=True)),
                ('label', models.CharField(default='', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='create_by',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='update_by',
            field=models.CharField(default='', max_length=256),
        ),
    ]
