# Generated by Django 2.1.7 on 2020-01-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20191231_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
