# Generated by Django 2.1.7 on 2020-01-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20200102_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('create_date', models.CharField(default='', max_length=45)),
                ('create_time', models.IntegerField(default=0)),
                ('update_time', models.IntegerField(default=0)),
                ('update_date', models.CharField(default='', max_length=45)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256)),
                ('update_by', models.CharField(default='', max_length=256)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(default='', max_length=256)),
                ('method', models.CharField(default='', max_length=256)),
                ('json', models.CharField(default='', max_length=512)),
                ('ip', models.CharField(default='', max_length=56)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
