# Generated by Django 2.1.7 on 2020-01-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20200103_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='data_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
