# Generated by Django 2.1.7 on 2020-01-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20200103_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='obj',
            field=models.CharField(default='', max_length=256),
        ),
    ]
