# Generated by Django 2.1.7 on 2020-01-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_log_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remarks',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
