# Generated by Django 2.1.7 on 2020-01-07 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_user_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telephone',
            new_name='phone',
        ),
    ]
