# Generated by Django 2.1.7 on 2020-01-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_auto_20200107_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='json',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
