# Generated by Django 2.1.7 on 2020-01-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_auto_20200107_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('create_date', models.CharField(default='', max_length=45)),
                ('create_time', models.IntegerField(default=0)),
                ('update_time', models.IntegerField(default=0)),
                ('update_date', models.CharField(default='', max_length=45)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256)),
                ('update_by', models.CharField(default='', max_length=256)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256)),
                ('role_type', models.CharField(default='', max_length=256)),
                ('useable', models.CharField(default='', max_length=256)),
                ('remarks', models.CharField(default='', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
