# Generated by Django 2.1.7 on 2020-01-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_auto_20200108_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='office',
            fields=[
                ('create_date', models.CharField(default='', max_length=45)),
                ('create_time', models.IntegerField(default=0)),
                ('update_time', models.IntegerField(default=0)),
                ('update_date', models.CharField(default='', max_length=45)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256)),
                ('update_by', models.CharField(default='', max_length=256)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.CharField(default='', max_length=256)),
                ('parent_ids', models.CharField(default='', max_length=256)),
                ('sort', models.IntegerField(default=0)),
                ('area_id', models.CharField(default='', max_length=256, null=True)),
                ('code', models.CharField(default='', max_length=256)),
                ('useable', models.IntegerField(default=1)),
                ('remarks', models.CharField(default='', max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
