# Generated by Django 2.1.7 on 2020-01-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict',
            name='create_by',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='dict',
            name='create_date',
            field=models.CharField(default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='dict',
            name='create_time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dict',
            name='update_by',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='dict',
            name='update_date',
            field=models.CharField(default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='dict',
            name='update_time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='create_by',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='create_date',
            field=models.CharField(default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='create_time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='update_by',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='update_date',
            field=models.CharField(default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='update_time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='create_by',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='create_date',
            field=models.CharField(default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='create_time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='update_by',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='update_date',
            field=models.CharField(default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='update_time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='create_by',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='create_date',
            field=models.CharField(default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='create_time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='update_by',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='update_date',
            field=models.CharField(default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='update_time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_by',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_date',
            field=models.CharField(default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_by',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_date',
            field=models.CharField(default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
