# Generated by Django 2.1.7 on 2020-01-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_auto_20200110_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='type',
            field=models.CharField(default='', max_length=64, null=True),
        ),
    ]
