# Generated by Django 2.1.7 on 2020-01-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_office_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='parent_name',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
