# Generated by Django 2.1.7 on 2020-01-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_office_parent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='office_id',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
