# Generated by Django 2.1.7 on 2020-01-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_user_office_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='office_name',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
