# Generated by Django 2.1.7 on 2020-01-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_user_office_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='log',
            name='user_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
