# Generated by Django 2.1.7 on 2020-01-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0028_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.CharField(default='', max_length=56, null=True)),
                ('parent_ids', models.CharField(default='', max_length=256, null=True)),
                ('name', models.CharField(default='', max_length=256)),
                ('sort', models.IntegerField(default=0)),
                ('href', models.CharField(default='', max_length=256, null=True)),
                ('is_show', models.IntegerField(default=0)),
                ('menu_type', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
