# Generated by Django 2.1.7 on 2020-02-10 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0029_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='role_menu',
            fields=[
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='menu_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='user_role',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='user_role',
            name='user_id',
        ),
        migrations.AddField(
            model_name='menu',
            name='base_href',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='has_children',
            field=models.CharField(default='false', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='parent_name',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='remarks',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user_role',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.role'),
        ),
        migrations.AddField(
            model_name='user_role',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.user'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='role_menu',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.menu'),
        ),
        migrations.AddField(
            model_name='role_menu',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.role'),
        ),
    ]
