# Generated by Django 2.1.7 on 2020-02-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0030_auto_20200210_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='template',
            fields=[
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template_type', models.IntegerField(default=0)),
                ('template_name', models.CharField(default='', max_length=256)),
                ('fileName', models.CharField(default='', max_length=256)),
                ('fileExtension', models.CharField(default='', max_length=256)),
                ('templateJson', models.CharField(default='', max_length=2048)),
                ('template', models.CharField(default='', max_length=2048)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
