# Generated by Django 2.1.7 on 2020-02-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0031_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='fileExtension',
            new_name='file_extension',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='fileName',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='templateJson',
            new_name='template_json',
        ),
    ]
