# Generated by Django 2.1.7 on 2020-02-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0032_auto_20200213_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_rule',
            fields=[
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_id', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=256)),
                ('r_filed', models.CharField(default='', max_length=256)),
                ('r_express', models.CharField(default='', max_length=256)),
                ('r_value', models.CharField(default='', max_length=256)),
                ('class_ame', models.CharField(default='', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='template',
            name='file_extension',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_type',
            field=models.CharField(default='', max_length=256),
        ),
    ]
