# Generated by Django 2.1.7 on 2020-02-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0033_auto_20200224_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_rule',
            old_name='class_ame',
            new_name='class_name',
        ),
    ]
