# Generated by Django 2.1.7 on 2020-02-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0034_auto_20200224_1331'),
    ]

    operations = [

        migrations.AddField(
            model_name='data_rule',
            name='remarks',
            field=models.CharField(default='', max_length=256),
        ),
    ]
