# Generated by Django 2.1.7 on 2020-02-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0035_auto_20200224_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='role_data_rule',
            fields=[
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_id', models.IntegerField(default=0)),
                ('data_rule_id', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='template',
            old_name='template',
            new_name='template_text',
        ),
    ]
