# Generated by Django 2.1.7 on 2020-02-24 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0036_auto_20200224_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role_data_rule',
            name='data_rule_id',
        ),
        migrations.RemoveField(
            model_name='role_data_rule',
            name='role_id',
        ),
        migrations.AddField(
            model_name='role_data_rule',
            name='data_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.data_rule'),
        ),
        migrations.AddField(
            model_name='role_data_rule',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.role'),
        ),
    ]
