# Generated by Django 2.1.7 on 2020-03-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0037_auto_20200224_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='dict_type',
            field=models.CharField(default='', max_length=256),
        ),
    ]
