# Generated by Django 2.1.7 on 2020-03-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0038_template_dict_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='message_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('message_id', models.CharField(max_length=20)),
                ('user_id', models.IntegerField()),
                ('message_type', models.CharField(max_length=20)),
                ('message_tag', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('send_time', models.CharField(max_length=255)),
                ('confirm_time', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
