# Generated by Django 2.1 on 2020-04-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0040_create_pdf_log_send_email_log_sgd_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='create_pdf_log',
            new_name='sgd_email_log',
        ),
        migrations.RenameModel(
            old_name='send_email_log',
            new_name='sgd_pdf_log',
        ),
    ]
