# Generated by Django 2.1 on 2020-04-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0041_auto_20200402_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgd_user',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
