# Generated by Django 2.1 on 2020-04-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0042_sgd_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgd_user',
            name='is_lock',
            field=models.IntegerField(default=0),
        ),
    ]
