# Generated by Django 2.1 on 2020-04-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0043_sgd_user_is_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgd_user',
            name='pdf_pwd',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
