# Generated by Django 2.1 on 2020-04-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0044_sgd_user_pdf_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgd_user',
            name='expire_date',
            field=models.CharField(default='', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='sgd_user',
            name='extension',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sgd_user',
            name='original_expire_date',
            field=models.CharField(default='', max_length=45, null=True),
        ),
    ]
