# Generated by Django 2.1 on 2020-04-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0045_auto_20200407_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sgd_user',
            old_name='expire_date',
            new_name='extension_expire_date',
        ),
    ]
