# Generated by Django 2.1 on 2020-04-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0046_auto_20200407_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgd_pdf_log',
            name='pdf_path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
