# Generated by Django 2.1 on 2020-04-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0047_sgd_pdf_log_pdf_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ldap',
            field=models.IntegerField(default=0),
        ),
    ]
