# Generated by Django 2.1 on 2020-04-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0048_user_ldap'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ldap_group',
            field=models.IntegerField(default=0),
        ),
    ]
