# Generated by Django 2.1.7 on 2020-05-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0049_user_ldap_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='sync_config',
            fields=[
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=255)),
                ('enable', models.BooleanField(default=0)),
                ('mode', models.IntegerField(default=0)),
                ('day_of_week', models.CharField(max_length=255)),
                ('hour', models.IntegerField(default=0)),
                ('minute', models.IntegerField(default=0)),
                ('second', models.IntegerField(default=0)),
                ('ldap_server_pool', models.CharField(max_length=255)),
                ('ldap_server_port', models.CharField(max_length=255)),
                ('admin_dn', models.CharField(max_length=255)),
                ('admin_pwd', models.CharField(max_length=255)),
                ('search_base', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
