# Generated by Django 2.1.7 on 2020-05-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0050_sync_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sync_config',
            old_name='plan_name',
            new_name='sync_name',
        ),
    ]
