# Generated by Django 2.1.7 on 2020-05-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0051_auto_20200512_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sync_config',
            name='mode',
            field=models.CharField(max_length=255),
        ),
    ]
