# Generated by Django 2.1.7 on 2020-05-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0052_auto_20200514_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='sync_log',
            fields=[
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('config_id', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
                ('add', models.IntegerField(default=0)),
                ('cancel', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='sync_log_detail',
            fields=[
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_id', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
