# Generated by Django 2.1.7 on 2020-05-16 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0053_sync_log_sync_log_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sync_log',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 17, 15, 59, 872887)),
        ),
    ]
