# Generated by Django 2.1.7 on 2020-05-16 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0054_auto_20200516_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sync_log',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='sync_log',
            name='start_time',
        ),
        migrations.AddField(
            model_name='sync_log',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sync_log',
            name='finished',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sync_log',
            name='run_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 17, 25, 56, 570147)),
        ),
        migrations.AddField(
            model_name='sync_log',
            name='started',
            field=models.FloatField(default=0),
        ),
    ]
