# Generated by Django 2.1.7 on 2020-05-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0055_auto_20200516_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='sync_log',
            name='remark',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sync_log',
            name='run_time',
            field=models.DateTimeField(default='2020-05-19 13:53:56'),
        ),
    ]
