# Generated by Django 2.1.7 on 2020-05-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0056_auto_20200519_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='sync_log',
            name='enable',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sync_log',
            name='run_time',
            field=models.DateTimeField(default='1970-01-01'),
        ),
    ]
