# Generated by Django 2.1.7 on 2020-05-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0057_auto_20200521_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sync_config',
            name='day_of_week',
        ),
    ]
