# Generated by Django 2.1.7 on 2020-05-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0058_remove_sync_config_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sync_config',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='sync_config',
            name='minute',
        ),
    ]
