# Generated by Django 2.1.7 on 2020-05-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0059_auto_20200522_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='sync_config',
            name='mode_time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
