# Generated by Django 2.1.7 on 2020-05-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0060_sync_config_mode_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sync_config',
            name='second',
        ),
        migrations.AlterField(
            model_name='sync_config',
            name='mode_time',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
