# Generated by Django 2.1.7 on 2020-06-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0061_auto_20200522_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_check',
            fields=[
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info_id', models.IntegerField(default=0)),
                ('iems_record_no', models.CharField(blank=True, max_length=20, null=True)),
                ('analysis_status', models.IntegerField(default=0)),
                ('analysis_message', models.CharField(blank=True, max_length=255, null=True)),
                ('result_file_name', models.CharField(max_length=500)),
                ('result', models.CharField(max_length=500)),
                ('precision', models.CharField(max_length=255)),
                ('precision_check_status', models.IntegerField(default=0)),
                ('topcell', models.CharField(max_length=255)),
                ('topcell_check_status', models.IntegerField(default=0)),
                ('layers', models.CharField(max_length=255)),
                ('layers_check_status', models.IntegerField(default=0)),
                ('bbox', models.CharField(max_length=255)),
                ('bbox_check_status', models.IntegerField(default=0)),
                ('analysis_check_status', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='upload_info',
            fields=[
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('file_path', models.CharField(max_length=255)),
                ('file_check_type', models.CharField(max_length=255)),
                ('file_check_value', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='upload_log',
            fields=[
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('file_path', models.CharField(max_length=255)),
                ('upload_status', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
