# Generated by Django 2.1.7 on 2020-06-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0062_upload_check_upload_info_upload_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upload_check',
        ),
        migrations.DeleteModel(
            name='upload_log',
        ),
        migrations.AddField(
            model_name='upload_info',
            name='analysis_check_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upload_info',
            name='analysis_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='upload_info',
            name='analysis_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upload_info',
            name='bbox',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='upload_info',
            name='bbox_check_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upload_info',
            name='iems_record_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='upload_info',
            name='layers',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='upload_info',
            name='layers_check_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upload_info',
            name='precision',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='upload_info',
            name='precision_check_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upload_info',
            name='result',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='upload_info',
            name='result_file_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='upload_info',
            name='sub_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='upload_info',
            name='topcell',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='upload_info',
            name='topcell_check_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='upload_info',
            name='file_check_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='upload_info',
            name='file_check_value',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='upload_info',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='upload_info',
            name='file_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
