# Generated by Django 2.1.7 on 2020-06-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0063_auto_20200618_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_info',
            old_name='file_check_type',
            new_name='file_type',
        ),
        migrations.RenameField(
            model_name='upload_info',
            old_name='file_check_value',
            new_name='file_value',
        ),
        migrations.AddField(
            model_name='upload_info',
            name='file_size_check_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='upload_info',
            name='file_type_check_status',
            field=models.IntegerField(default=0),
        ),
    ]
