# Generated by Django 2.1.7 on 2020-06-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0064_auto_20200619_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_info',
            name='result',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
