# Generated by Django 2.1.7 on 2020-06-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0065_auto_20200628_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_info',
            name='layers',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AlterField(
            model_name='upload_info',
            name='result',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
