# Generated by Django 2.1.7 on 2020-07-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0066_auto_20200628_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_code',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
