# Generated by Django 2.1.7 on 2020-07-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0067_user_customer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_code_id',
            field=models.IntegerField(default=0),
        ),
    ]
