# Generated by Django 2.1.7 on 2020-08-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0068_user_customer_code_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_info',
            name='file_size',
            field=models.CharField(default='', max_length=255),
        ),
    ]
