# Generated by Django 2.1.7 on 2020-08-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0069_auto_20200803_1634'),
        ('system', '0069_sign_info_sign_log_sign_person'),
    ]

    operations = [
    ]
