# Generated by Django 2.1.7 on 2020-08-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0070_merge_20200804_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sign_info',
        ),
        migrations.DeleteModel(
            name='sign_log',
        ),
        migrations.DeleteModel(
            name='sign_person',
        ),
    ]
