# code = utf-8
'''
@Author:Ligo
@date:2020/3/20 16:41
@File:global.py
@Project:Mask_DP
desc:define global constant ,you can use it in html
'''
from utilslibrary.system_constant import Constant

def global_setting(request):
    content = {
    'LOT_STAGE_GEN_FILE_SUBMITTED':Constant.LOT_STAGE_GEN_FILE_SUBMITTED,
    'LOT_STAGE_GEN_FILE_ERROR':Constant.LOT_STAGE_GEN_FILE_ERROR,
    'LOT_STAGE_GEN_FILE_SUCCESS':Constant.LOT_STAGE_GEN_FILE_SUCCESS,
    'LOT_STAGE_FRACTURE_SUBMITTED':Constant.LOT_STAGE_FRACTURE_SUBMITTED,
    'LOT_STAGE_FRACTURE_ERROR':Constant.LOT_STAGE_FRACTURE_ERROR,
    'LOT_STAGE_FRACTURE_SUCCESS':Constant.LOT_STAGE_FRACTURE_SUCCESS,
    'LOT_STAGE_XOR_SUBMITED':  Constant.LOT_STAGE_XOR_SUBMITED,
    'LOT_STAGE_XOR_ERROR':Constant.LOT_STAGE_XOR_ERROR,
    'LOT_STAGE_XOR_SUCCESS':Constant.LOT_STAGE_XOR_SUCCESS,
    'LOT_STAGE_IS_ERROR_NO':Constant.LOT_STAGE_IS_ERROR_NO,
    'LOT_STAGE_IS_ERROR_YES':Constant.LOT_STAGE_IS_ERROR_YES,
    'CONVERT_STATUS_WAIT':Constant.CONVERT_STATUS_WAIT,
    'CONVERT_STATUS_ON_GOING':Constant.CONVERT_STATUS_ON_GOING,
    'CONVERT_STATUS_DONE':Constant.CONVERT_STATUS_DONE,
    'CONVERT_STATUS_JOB_FAIL':Constant.CONVERT_STATUS_JOB_FAIL,
    'CONVERT_STATUS_NO_CLEAN':Constant.CONVERT_STATUS_NO_CLEAN,
    'CONVERT_OPERATION_RELEASE':Constant.CONVERT_OPERATION_RELEASE,
    'CONVERT_OPERATION_SKIP':Constant.CONVERT_OPERATION_SKIP,
    'CONVERT_OPERATION_HOLD':Constant.CONVERT_OPERATION_HOLD,


    }
    return content

