# Generated by Django 2.1.7 on 2021-02-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unreleased_info',
            name='customer',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
