# Generated by Django 2.1.7 on 2021-02-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotree', '0002_unreleased_info_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintain_table',
            name='customer',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
