# Generated by Django 2.1.7 on 2021-02-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotree', '0003_maintain_table_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='released_info',
            name='customer',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='released_info_alta',
            name='customer',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='unreleased_info_alta',
            name='customer',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
