# Generated by Django 2.1.7 on 2021-02-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotree', '0004_auto_20210219_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_tree_data_import_temp',
            name='customer',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
