# Generated by Django 2.1.7 on 2021-02-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotree', '0005_info_tree_data_import_temp_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='release_check',
            name='customer',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
