# Generated by Django 2.1.7 on 2020-12-01 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('code', models.CharField(default='', max_length=10)),
                ('customer', models.CharField(default='', max_length=50)),
                ('remark', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='customer_ftp_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('customer_code', models.CharField(max_length=255)),
                ('ftp_ip', models.CharField(max_length=255)),
                ('account', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('ftp_path', models.CharField(max_length=255, null=True)),
                ('product', models.CharField(max_length=255, null=True)),
                ('enable', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='maintain_change_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=255)),
                ('data_id', models.IntegerField()),
                ('operation', models.CharField(default='', max_length=255)),
                ('upt_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('change_user', models.CharField(max_length=255)),
                ('old_data', models.TextField(default="{'No': 'Data'}")),
                ('new_data', models.TextField(default="{'No': 'Data'}")),
            ],
        ),
    ]
