# Generated by Django 2.1.7 on 2020-12-14 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0002_maintain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_in_table',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='data_in_table',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='data_in_table',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='data_in_table',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='data_in_table',
            name='update_by',
        ),
        migrations.RemoveField(
            model_name='data_in_table',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='data_in_table',
            name='update_time',
        ),
    ]
