# Generated by Django 2.1.7 on 2020-12-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0003_maintain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_in_table',
            old_name='id_delete',
            new_name='is_delete',
        ),
    ]
