# Generated by Django 2.1.7 on 2020-12-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0004_maintain'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_in_table',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
