# Generated by Django 2.1.7 on 2020-12-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0005_maintain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_in_table',
            name='date',
            field=models.IntegerField(null=True),
        ),
    ]
