# Generated by Django 2.1.7 on 2020-12-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0006_maintain'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_in_table',
            name='md5_pass',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
