# Generated by Django 2.1.7 on 2020-12-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0007_maintain'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_in_table',
            name='last_check_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='data_in_table',
            name='file_size',
            field=models.IntegerField(null=True),
        ),
    ]
