# Generated by Django 2.1.7 on 2020-12-16 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0008_maintain'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_in_table',
            name='upt_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='data_in_table',
            name='file_size',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='data_in_table',
            name='last_check_size',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
