# Generated by Django 2.1.7 on 2020-12-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0009_maintain'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_in_table',
            name='downloaded',
            field=models.IntegerField(default=0),
        ),
    ]
