# Generated by Django 2.1.7 on 2020-12-17 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0010_maintain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ftp_data_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('ftp_path', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('is_delete', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('date', models.IntegerField(null=True)),
                ('last_check_size', models.CharField(max_length=255, null=True)),
                ('upt_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('downloaded', models.IntegerField(default=0)),
            ],
        ),
    ]
