# Generated by Django 2.1.7 on 2020-12-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0011_maintain'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_ftp_account',
            name='date',
            field=models.IntegerField(null=True),
        ),
    ]
