# Generated by Django 2.1.7 on 2020-12-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0012_maintain'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_in_table',
            name='ftp_data_id',
            field=models.IntegerField(null=True),
        ),
    ]
