# Generated by Django 2.1.7 on 2020-12-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0014_maintain'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_in_table',
            name='serial_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
