# Generated by Django 2.1.7 on 2020-12-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0015_maintain'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftp_data_table',
            name='file_name_decrypt',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
