# Generated by Django 2.1.7 on 2021-01-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0016_maintain'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_ftp_account',
            name='ftp_port',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_ftp_account',
            name='ftp_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
