# Generated by Django 2.1.7 on 2021-01-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0017_maintain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_ftp_account',
            name='date',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
