# Generated by Django 2.1.7 on 2021-01-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0018_mmaintain'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftp_data_table',
            name='md5_pass',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ftp_data_table',
            name='md5sum',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
