# Generated by Django 2.1.7 on 2021-01-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0019_maintain'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftp_data_table',
            name='ftp_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
