# Generated by Django 2.1.7 on 2021-02-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0020_maintain'),
    ]

    operations = [
        migrations.CreateModel(
            name='retention_data_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftp_data_id', models.IntegerField(null=True)),
                ('customer', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('is_delete', models.IntegerField(default=0)),
                ('ship_time', models.DateTimeField(null=True)),
                ('expire_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
