# Generated by Django 2.1.7 on 2021-02-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintain', '0021_maintain'),
    ]

    operations = [
        migrations.AddField(
            model_name='retention_data_table',
            name='date',
            field=models.IntegerField(null=True),
        ),
    ]
