# Generated by Django 2.1 on 2020-02-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='machine_basic',
            fields=[
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_ip', models.CharField(max_length=256, null=True)),
                ('machine_type', models.CharField(max_length=256, null=True)),
                ('machine_account', models.CharField(max_length=256, null=True)),
                ('machine_password', models.CharField(max_length=256, null=True)),
                ('ftp_ip', models.CharField(max_length=256, null=True)),
                ('ftp_path', models.CharField(max_length=256, null=True)),
                ('ftp_account', models.CharField(max_length=256, null=True)),
                ('ftp_password', models.CharField(max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='machine_script_templates',
            fields=[
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_basic_id', models.IntegerField(default=0)),
                ('template_id', models.IntegerField(default=0)),
                ('template_type', models.CharField(default='', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
