# Generated by Django 2.1 on 2020-02-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_basic',
            name='machine_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
