# Generated by Django 2.1 on 2020-02-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_machine_basic_machine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_basic',
            name='machine_remark',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
