# Generated by Django 2.1.7 on 2020-03-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_machine_basic_machine_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='writer_mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('seq', models.IntegerField()),
                ('customer', models.CharField(max_length=100, null=True)),
                ('design_rule', models.CharField(max_length=100, null=True)),
                ('product', models.CharField(max_length=100, null=True)),
                ('layer_name', models.CharField(max_length=100, null=True)),
                ('product_type', models.CharField(max_length=100, null=True)),
                ('grade_form', models.CharField(max_length=100, null=True)),
                ('grade_to', models.CharField(max_length=100, null=True)),
                ('mask_type', models.CharField(max_length=100, null=True)),
                ('tone', models.CharField(max_length=100, null=True)),
                ('exp_tool', models.CharField(max_length=100, null=True)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('book_user_id', models.IntegerField()),
                ('book_user_name', models.CharField(max_length=255)),
                ('book_time', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
