# Generated by Django 2.1.7 on 2020-03-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_writer_mapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer_mapping',
            old_name='grade_form',
            new_name='grade_from',
        ),
    ]
