# Generated by Django 2.1.7 on 2020-03-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0005_auto_20200324_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer_mapping',
            name='machine_id',
            field=models.IntegerField(null=True),
        ),
    ]
