# Generated by Django 2.1.7 on 2020-09-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0006_writer_mapping_machine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer_mapping',
            name='catalog_tool_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='writer_mapping',
            name='info_tree_tool_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
