# Generated by Django 2.1.7 on 2020-04-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='convert_operate_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('convert_status_id', models.IntegerField()),
                ('operation', models.CharField(max_length=255)),
                ('operation_time', models.CharField(max_length=255)),
                ('operation_user_id', models.IntegerField(null=True)),
                ('operation_user_name', models.CharField(max_length=255)),
                ('remark', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='convert_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_no', models.CharField(max_length=255)),
                ('mask_name', models.CharField(max_length=255, null=True)),
                ('lot_id', models.CharField(max_length=255, null=True)),
                ('device_name', models.CharField(max_length=255)),
                ('stage_id', models.IntegerField(null=True)),
                ('stage', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('operation_status', models.IntegerField(default=0)),
                ('progress', models.FloatField(default=0.0)),
                ('remark', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='convert_status_stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=20)),
                ('flow', models.CharField(max_length=20)),
                ('pre_stage', models.CharField(max_length=255)),
                ('parent_stage_id', models.IntegerField(default=0)),
                ('operation', models.CharField(max_length=255)),
                ('type', models.IntegerField(default=1)),
                ('device_type', models.CharField(max_length=255)),
                ('order', models.IntegerField(null=True)),
                ('link', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
