# Generated by Django 2.1.7 on 2020-04-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0002_convert_operate_log_convert_status_convert_status_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='fracture_callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('record_no', models.CharField(max_length=255)),
                ('data_id', models.IntegerField(default=0, null=True)),
                ('result_code', models.IntegerField(default=0, null=True)),
                ('result_content', models.TextField(max_length=255)),
                ('callback_date', models.CharField(default='', max_length=10)),
                ('callback_time', models.IntegerField(default=0)),
                ('callback_return_status', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
