# Generated by Django 2.1.7 on 2020-04-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0003_fracture_callback'),
    ]

    operations = [
        migrations.AddField(
            model_name='convert_status',
            name='file_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='convert_status',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='convert_status',
            name='stage',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='convert_status',
            name='tip_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='convert_status_stage',
            name='device_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='convert_status_stage',
            name='flow',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='convert_status_stage',
            name='operation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='convert_status_stage',
            name='order',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='convert_status_stage',
            name='pre_stage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='convert_status_stage',
            name='stage_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
