# Generated by Django 2.1.7 on 2020-04-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0004_auto_20200409_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convert_status',
            name='progress',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
