# Generated by Django 2.1.7 on 2020-04-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0004_auto_20200409_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fracture_callback',
            name='callback_date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
