# Generated by Django 2.1.7 on 2020-04-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0005_auto_20200410_0907'),
        ('making', '0005_auto_20200410_0930'),
    ]

    operations = [
    ]
