# Generated by Django 2.1.7 on 2020-04-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0006_merge_20200415_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='record_id_lot_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('lot_id', models.CharField(max_length=255)),
                ('convert_status_id', models.CharField(max_length=255)),
                ('tip_no', models.CharField(max_length=255)),
                ('mask_name', models.CharField(max_length=255)),
                ('device_name', models.CharField(max_length=255)),
                ('record_no', models.CharField(max_length=255)),
                ('param', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('result', models.TextField()),
                ('message', models.CharField(max_length=255)),
                ('submit_time', models.TimeField(null=True)),
                ('callback_time', models.TimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
