# Generated by Django 2.1.7 on 2020-04-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0007_making'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='record_id_lot_id',
            new_name='record_no_lot_id',
        ),
    ]
