# Generated by Django 2.1.7 on 2020-04-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0008_making'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='record_no_lot_id',
            new_name='iems_record_msg',
        ),
    ]
