# Generated by Django 2.1.7 on 2020-04-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0009_making'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iems_record_msg',
            name='callback_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='iems_record_msg',
            name='submit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
