# Generated by Django 2.1.7 on 2020-04-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0012_making'),
    ]

    operations = [
        migrations.AddField(
            model_name='convert_operate_log',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='convert_operate_log',
            name='result',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='convert_operate_log',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
