# Generated by Django 2.1.7 on 2020-04-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0013_making'),
    ]

    operations = [
        migrations.AddField(
            model_name='convert_operate_log',
            name='params',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='convert_operate_log',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
