# Generated by Django 2.1.7 on 2020-04-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0014_making'),
    ]

    operations = [
        migrations.AddField(
            model_name='convert_operate_log',
            name='code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='convert_status',
            name='operator',
            field=models.CharField(default='', max_length=255),
        ),
    ]
