# Generated by Django 2.1.7 on 2020-04-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0015_making'),
    ]

    operations = [
        migrations.AddField(
            model_name='convert_operate_log',
            name='device_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='convert_operate_log',
            name='mask_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='convert_operate_log',
            name='record_no',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='convert_operate_log',
            name='submit_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='convert_operate_log',
            name='result',
            field=models.CharField(default='', max_length=255),
        ),
    ]
