# Generated by Django 2.1.7 on 2020-04-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0016_making'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convert_operate_log',
            name='result',
            field=models.TextField(null=True),
        ),
    ]
