# Generated by Django 2.1.7 on 2020-04-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0017_making'),
    ]

    operations = [
        migrations.AddField(
            model_name='convert_status',
            name='record_no',
            field=models.CharField(default='', max_length=255),
        ),
    ]
