# Generated by Django 2.1.7 on 2020-04-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0018_making'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fracture_callback',
            name='data_id',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
