# Generated by Django 2.1.7 on 2020-04-26 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0020_making'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fracture_callback',
            name='data_id',
        ),
    ]
