# Generated by Django 2.1.7 on 2020-04-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0022_making'),
    ]

    operations = [
        migrations.AddField(
            model_name='convert_status',
            name='progress_history',
            field=models.CharField(default='0%', max_length=255),
        ),
    ]
