# Generated by Django 2.1.7 on 2020-05-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0024_making'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convert_status',
            name='progress',
            field=models.CharField(default='0.00%', max_length=255),
        ),
        migrations.AlterField(
            model_name='convert_status',
            name='progress_history',
            field=models.TextField(default='0.00%'),
        ),
    ]
