# Generated by Django 2.1.7 on 2020-06-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0025_full_tooling'),
    ]

    operations = [
        migrations.CreateModel(
            name='deck_para',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('node', models.CharField(max_length=10)),
                ('stage', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=50, null=True)),
                ('function', models.CharField(max_length=50, null=True)),
                ('item', models.CharField(max_length=255)),
                ('ref1', models.CharField(max_length=255, null=True)),
                ('ref2', models.CharField(max_length=255, null=True)),
                ('ref3', models.CharField(max_length=255, null=True)),
                ('ref4', models.CharField(max_length=255, null=True)),
                ('value_in', models.CharField(max_length=255, null=True)),
                ('value_out', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
