# Generated by Django 2.1.7 on 2020-06-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0026_making'),
    ]

    operations = [
        migrations.CreateModel(
            name='fracture_deck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255, null=True)),
                ('file', models.CharField(max_length=50, null=True)),
                ('layer', models.CharField(max_length=255, null=True)),
                ('format', models.CharField(max_length=50, null=True)),
                ('db_count', models.IntegerField(default=1)),
            ],
        ),
    ]
