# Generated by Django 2.1.7 on 2020-06-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0027_making'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck_para',
            name='db_count',
            field=models.IntegerField(default=1),
        ),
    ]
