# Generated by Django 2.1.7 on 2020-07-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0028_making'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mdt_cad_layer',
        ),
        migrations.DeleteModel(
            name='mdt_info',
        ),
    ]
