# Generated by Django 2.1.7 on 2020-07-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0029_auto_20200702_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='convert_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tip_no', models.CharField(max_length=50)),
                ('mask_name', models.CharField(max_length=50)),
                ('device_name', models.CharField(max_length=50)),
                ('stage_list', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50, null=True)),
                ('opc_tool', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='convert_table_time',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('convert_table_id', models.IntegerField()),
                ('stage', models.CharField(max_length=50)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('result', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
