# Generated by Django 2.1.7 on 2020-09-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0030_making'),
    ]

    operations = [
        migrations.CreateModel(
            name='alta_naming_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=50)),
                ('prod_serial', models.CharField(max_length=50)),
                ('device_name', models.CharField(max_length=50)),
                ('device_serial', models.CharField(max_length=50)),
                ('layer', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('alta_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='convert_status',
            name='alta_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
