# Generated by Django 2.1.7 on 2020-09-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0031_making'),
    ]

    operations = [
        migrations.AddField(
            model_name='alta_naming_table',
            name='submit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='alta_naming_table',
            name='version_serial',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
