# Generated by Django 2.1.7 on 2020-09-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0032_auto_20200916_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='alta_naming_table',
            name='mask_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alta_naming_table',
            name='tip_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
