# Generated by Django 2.1.7 on 2020-09-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0033_auto_20200916_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='convert_status',
            name='err_message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
