# Generated by Django 2.1.7 on 2020-10-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0034_convert_status_err_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='fracture_deck',
            name='stage_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
