# Generated by Django 2.1.7 on 2020-09-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_maintain',
            name='tool_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
