# Generated by Django 2.1.7 on 2020-09-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_group_maintain_tool_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_maintain',
            name='info_tree_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
