# Generated by Django 2.1.7 on 2020-09-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_group_maintain_info_tree_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool_maintain',
            old_name='group_id',
            new_name='exptool',
        ),
        migrations.RenameField(
            model_name='tool_maintain',
            old_name='tool_code',
            new_name='group_name',
        ),
    ]
