# Generated by Django 2.1.7 on 2020-09-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_tool_name_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_maintain',
            name='machine_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
