# Generated by Django 2.1.7 on 2020-09-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_group_maintain_machine_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_maintain',
            name='machine_type',
        ),
        migrations.AddField(
            model_name='tool_name_route',
            name='machine_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
