# Generated by Django 2.1.7 on 2020-10-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200925_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool_maintain',
            name='account',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tool_maintain',
            name='ip',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tool_maintain',
            name='passord',
            field=models.CharField(default='', max_length=255),
        ),
    ]
