# Generated by Django 2.1.7 on 2020-10-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20201023_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool_maintain',
            old_name='passord',
            new_name='password',
        ),
        migrations.AddField(
            model_name='tool_maintain',
            name='path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tool_maintain',
            name='tool_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
