# Generated by Django 2.1.7 on 2020-07-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iems_execute_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_no', models.CharField(max_length=255)),
                ('execute_start_time', models.DateTimeField()),
                ('execute_end_time', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('execute_result', models.TextField()),
                ('job_id', models.CharField(max_length=255)),
            ],
        ),
    ]
