# Generated by Django 2.1.7 on 2020-07-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iems', '0004_iems_execute_result_result_log_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iems_execute_result',
            name='execute_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='iems_execute_result',
            name='execute_result',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='iems_execute_result',
            name='execute_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
