# Generated by Django 2.1.7 on 2020-02-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='email_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_id', models.IntegerField(default=0)),
                ('office_name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(default=0)),
                ('user_loginname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'email_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='lot_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('tip_no', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('release_status', models.IntegerField(default=0)),
                ('compile_status', models.IntegerField(default=0)),
                ('lot', models.CharField(max_length=255)),
                ('layer', models.CharField(max_length=255)),
                ('lot_owner_id', models.CharField(max_length=255)),
                ('lot_owner_name', models.CharField(max_length=255)),
                ('ready_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('status_dec', models.CharField(max_length=255)),
                ('payment_status', models.IntegerField(default=0)),
                ('payment_user_id', models.CharField(max_length=255)),
                ('payment_user_name', models.CharField(max_length=255)),
                ('payment_check_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
