# Generated by Django 2.1.7 on 2020-02-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lot_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('tip_no', models.CharField(max_length=20)),
                ('lot_id', models.CharField(max_length=255)),
                ('lot_name', models.CharField(max_length=255)),
                ('lot_owner_id', models.IntegerField()),
                ('lot_owner_name', models.CharField(max_length=255)),
                ('lot_id_create_date', models.DateTimeField()),
                ('lot_status', models.IntegerField(default=0)),
                ('lot_now_stage', models.CharField(max_length=255)),
                ('lot_trail', models.CharField(max_length=255)),
                ('lot_ready_date', models.DateTimeField()),
                ('lot_expire_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='lot_trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(max_length=32)),
                ('stage', models.CharField(max_length=255)),
                ('stage_status', models.IntegerField(default=0)),
                ('stage_desc', models.CharField(max_length=255)),
                ('stage_start_date', models.DateTimeField()),
                ('stage_end_date', models.DateTimeField()),
                ('operator_id', models.IntegerField()),
                ('operator_name', models.CharField(max_length=255)),
                ('operator_date', models.DateTimeField()),
                ('remark', models.CharField(max_length=255)),
            ],
        ),
    ]
