# Generated by Django 2.1.7 on 2020-02-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0002_lot_status_lot_trail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot_trail',
            old_name='operator_date',
            new_name='operate_date',
        ),
        migrations.AddField(
            model_name='lot_trail',
            name='tip_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
