# Generated by Django 2.1 on 2020-03-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0003_auto_20200227_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='mdt_cad_layer',
            fields=[
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('layer_id', models.AutoField(primary_key=True, serialize=False)),
                ('cad_layer', models.CharField(max_length=256, null=True)),
                ('data_type', models.CharField(max_length=256, null=True)),
                ('writer_mdt', models.CharField(max_length=256, null=True)),
                ('writer_dose', models.CharField(max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='mdt_info',
            fields=[
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('mdt_id', models.AutoField(primary_key=True, serialize=False)),
                ('design_rule', models.FloatField(null=True)),
                ('layer_name', models.CharField(max_length=256, null=True)),
                ('layer_define', models.CharField(max_length=256, null=True)),
                ('mask_tone', models.CharField(max_length=256, null=True)),
                ('mask_grade', models.CharField(max_length=256, null=True)),
                ('tooling_bias', models.CharField(max_length=256, null=True)),
                ('mdt', models.BooleanField()),
                ('remark', models.CharField(max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
