# Generated by Django 2.1 on 2020-03-02 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0004_mdt_cad_layer_mdt_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mdt_info',
            old_name='mdt_id',
            new_name='id',
        ),
    ]
