# Generated by Django 2.1 on 2020-03-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0005_auto_20200302_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mdt_cad_layer',
            old_name='layer_id',
            new_name='id',
        ),
    ]
