# Generated by Django 2.1 on 2020-03-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0006_auto_20200302_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdt_info',
            name='user_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
