# Generated by Django 2.1 on 2020-03-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0007_mdt_info_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdt_cad_layer',
            name='mdt_id',
            field=models.IntegerField(default=0),
        ),
    ]
