# Generated by Django 2.1 on 2020-03-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0008_mdt_cad_layer_mdt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdt_info',
            name='mdt',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
