# Generated by Django 2.1 on 2020-03-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0009_auto_20200304_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdt_info',
            name='tooling_bias',
            field=models.FloatField(null=True),
        ),
    ]
