# Generated by Django 2.1.7 on 2020-03-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0010_auto_20200312_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot_info',
            name='expire_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lot_info',
            name='payment_check_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lot_info',
            name='ready_date',
            field=models.DateTimeField(null=True),
        ),
    ]
