# Generated by Django 2.1.7 on 2020-03-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0011_auto_20200316_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot_info',
            old_name='layer',
            new_name='lot_id',
        ),
        migrations.RenameField(
            model_name='lot_info',
            old_name='lot',
            new_name='mask_name',
        ),
        migrations.AddField(
            model_name='lot_info',
            name='result',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
