# Generated by Django 2.1.7 on 2020-03-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0011_auto_20200316_1417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mdt_cad_layer',
        ),
        migrations.DeleteModel(
            name='mdt_info',
        ),
    ]
