# Generated by Django 2.1.7 on 2020-03-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0012_auto_20200318_1522'),
        ('jdv', '0012_auto_20200318_1610'),
    ]

    operations = [
    ]
