# Generated by Django 2.1.7 on 2020-03-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0013_merge_20200319_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot_info',
            name='convert_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='convert_status_dec',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
