# Generated by Django 2.1.7 on 2020-03-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0014_auto_20200319_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot_trail',
            name='create_by',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lot_trail',
            name='create_date',
            field=models.CharField(default='', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='lot_trail',
            name='create_time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='lot_trail',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lot_trail',
            name='update_by',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='lot_trail',
            name='update_date',
            field=models.CharField(default='', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='lot_trail',
            name='update_time',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
