# Generated by Django 2.1.7 on 2020-03-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0015_auto_20200319_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot_trail',
            name='is_error',
            field=models.IntegerField(default=0),
        ),
    ]
