# Generated by Django 2.1.7 on 2020-03-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0016_lot_trail_is_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot_trail',
            name='stage_desc',
            field=models.CharField(max_length=1024),
        ),
    ]
