# Generated by Django 2.1.7 on 2020-03-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0016_lot_trail_is_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot_info',
            name='mes_auto_dispatch_controller_flag',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_backup_processing_flag',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_bank_in_required_flag',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_bonding_group_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_carrier_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_completion_timestamp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_control_use_state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_current_location_flag',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_customer_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_due_timestamp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_eqp_monitor_job_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_equipment_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_get_wip_result',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_hold_reason_code_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_in_post_process_flag_of_cassette',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_in_post_process_flag_of_lot',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_inter_fab_xfer_state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_last_claimed_timestamp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_lot_family_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_lot_finished_state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_lot_hold_state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_lot_info_change_flag',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_lot_inventory_state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_lot_owener_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_lot_process_state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_lot_production_state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_lot_state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_lot_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_lot_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_operation_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_operation_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_order_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_pd_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_plan_start_timestamp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_priority_class',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_product_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_product_request_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_required_cassette_category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_route_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_schedule_mode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_sorter_job_exist_flag',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_sub_lot_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_total_wafer_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_transfer_flag',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_use_count',
            field=models.IntegerField(null=True),
        ),
    ]
