# Generated by Django 2.1.7 on 2020-03-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0017_auto_20200320_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot_info',
            name='mes_bank_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_get_wip_message',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
