# Generated by Django 2.1.7 on 2020-03-20 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0018_auto_20200320_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot_info',
            old_name='mes_lot_owener_id',
            new_name='mes_lot_owner_id',
        ),
        migrations.RenameField(
            model_name='lot_info',
            old_name='mes_use_count',
            new_name='mes_used_count',
        ),
    ]
