# Generated by Django 2.1.7 on 2020-03-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0017_auto_20200320_1457'),
        ('jdv', '0019_auto_20200320_1549'),
    ]

    operations = [
    ]
