# Generated by Django 2.1.7 on 2020-03-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0020_merge_20200323_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='lot_op_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(max_length=255)),
                ('equipment_id', models.CharField(max_length=255, null=True)),
                ('dp_operation', models.CharField(max_length=255, null=True)),
                ('mes_operation', models.CharField(max_length=255, null=True)),
                ('control_job_id', models.CharField(max_length=255, null=True)),
                ('op_operation_type', models.IntegerField(default=0)),
                ('op_operation', models.CharField(max_length=255, null=True)),
                ('op_operation_status', models.IntegerField(default=0)),
                ('mes_transaction_id', models.CharField(max_length=255, null=True)),
                ('op_operation_message', models.CharField(max_length=255, null=True)),
                ('op_operationt_date', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
