# Generated by Django 2.1.7 on 2020-03-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0021_lot_op_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot_info',
            name='clip',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='customer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='dispatch_flag',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='exp_tool',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='exp_tool_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='grade',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='mes_step',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='rule',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='tone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lot_info',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
