# Generated by Django 2.1.7 on 2020-03-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0022_auto_20200324_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot_info',
            name='machine_id',
            field=models.IntegerField(null=True),
        ),
    ]
