# Generated by Django 2.1.7 on 2020-03-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0023_lot_info_machine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot_info',
            name='dispatch_flag',
            field=models.IntegerField(default=0),
        ),
    ]
