# Generated by Django 2.1.7 on 2020-04-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0024_auto_20200325_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='mes_blank_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.CharField(default='', max_length=45, null=True)),
                ('create_time', models.IntegerField(default=0, null=True)),
                ('update_time', models.IntegerField(default=0, null=True)),
                ('update_date', models.CharField(default='', max_length=45, null=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('create_by', models.CharField(default='', max_length=256, null=True)),
                ('update_by', models.CharField(default='', max_length=256, null=True)),
                ('seq', models.IntegerField()),
                ('customer', models.CharField(max_length=255)),
                ('design_rule', models.CharField(max_length=255)),
                ('grade_from', models.CharField(max_length=255)),
                ('grade_to', models.CharField(max_length=255)),
                ('layer_name', models.CharField(max_length=255)),
                ('mask_type', models.CharField(max_length=255)),
                ('tone', models.CharField(max_length=255)),
                ('wave_lenght', models.CharField(max_length=255)),
                ('blank_code', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
