# Generated by Django 2.1.7 on 2020-04-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0025_jdv'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot_info',
            name='blank_code',
            field=models.IntegerField(default=0),
        ),
    ]
