# Generated by Django 2.1.7 on 2020-04-15 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0026_jdv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mes_blank_code',
            old_name='grade_from',
            new_name='grade',
        ),
        migrations.RemoveField(
            model_name='mes_blank_code',
            name='grade_to',
        ),
    ]
