# Generated by Django 2.1.7 on 2020-04-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0027_jdv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mes_blank_code',
            name='grade',
        ),
        migrations.AddField(
            model_name='mes_blank_code',
            name='grade_from',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mes_blank_code',
            name='grade_to',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
