# Generated by Django 2.1.7 on 2020-04-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0028_jdv'),
    ]

    operations = [
        migrations.CreateModel(
            name='mes_operation_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.IntegerField()),
                ('route_id', models.CharField(max_length=255, null=True)),
                ('operation_id', models.CharField(max_length=255, null=True)),
                ('operation_number', models.CharField(max_length=255, null=True)),
                ('pdType', models.CharField(max_length=255, null=True)),
                ('stage_id', models.CharField(max_length=255, null=True)),
                ('stage_group_id', models.CharField(max_length=255, null=True)),
                ('machines', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
