# Generated by Django 2.1.7 on 2020-04-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0029_mes_operation_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot_info',
            name='wavelength',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
