# Generated by Django 2.1.7 on 2020-09-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0031_lot_op_record_info_tree_tool_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot_op_record',
            name='info_tree_tool_id',
        ),
        migrations.AddField(
            model_name='lot_info',
            name='info_tree_tool_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
