# Generated by Django 2.1.7 on 2020-09-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0032_auto_20200908_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot_info',
            name='info_tree_tool_id',
        ),
    ]
