# Generated by Django 2.1.7 on 2020-09-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0033_remove_lot_info_info_tree_tool_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot_info',
            name='info_tree_tool_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
