# Generated by Django 2.1.7 on 2020-09-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0035_auto_20200918_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='mes_blank_code',
            name='blank',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mes_blank_code',
            name='part_no',
            field=models.CharField(default='', max_length=255),
        ),
    ]
