# Generated by Django 2.1.7 on 2020-09-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0036_auto_20200918_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot_info',
            name='ftp_upload_status',
            field=models.IntegerField(default=0),
        ),
    ]
