# Generated by Django 2.1.7 on 2020-09-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0037_lot_info_ftp_upload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot_info',
            name='catalog_status',
            field=models.IntegerField(default=0),
        ),
    ]
