# Generated by Django 2.1.7 on 2020-09-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0038_lot_info_catalog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot_info',
            name='ftp_error_message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
