# Generated by Django 2.1.7 on 2020-10-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0039_lot_info_ftp_error_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot_info',
            old_name='ftp_error_message',
            new_name='ftp_upload_error_message',
        ),
        migrations.AddField(
            model_name='lot_info',
            name='catalog_error_message',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='writer_create_file_error_message',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='writer_create_file_status',
            field=models.IntegerField(default=0),
        ),
    ]
