# Generated by Django 2.1.7 on 2020-10-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0040_auto_20201016_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot_info',
            name='catalog_error_message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lot_info',
            name='ftp_upload_error_message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lot_info',
            name='writer_create_file_error_message',
            field=models.TextField(null=True),
        ),
    ]
