# Generated by Django 2.1.7 on 2020-10-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0041_auto_20201016_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot_info',
            name='writer_create_file_error_message',
        ),
        migrations.RemoveField(
            model_name='lot_info',
            name='writer_create_file_status',
        ),
    ]
