# Generated by Django 2.1.7 on 2020-10-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0042_auto_20201017_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot_info',
            name='ftp_upload_error_message',
        ),
    ]
