# Generated by Django 2.1.7 on 2020-10-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0043_remove_lot_info_ftp_upload_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot_info',
            name='ftp_upload_error_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='writer_create_file_error_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='writer_create_file_status',
            field=models.IntegerField(default=0),
        ),
    ]
