# Generated by Django 2.1.7 on 2020-10-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0044_auto_20201017_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot_info',
            name='change_error_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='change_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='register_del_error_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='register_del_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='register_error_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='register_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='writer_over_error_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='writer_over_status',
            field=models.IntegerField(default=0),
        ),
    ]
