# Generated by Django 2.1.7 on 2020-11-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0045_auto_20201023_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lot_info',
            old_name='writer_over_error_message',
            new_name='writer_op_error_message',
        ),
        migrations.RenameField(
            model_name='lot_info',
            old_name='writer_over_status',
            new_name='writer_op_status',
        ),
    ]
