# Generated by Django 2.1.7 on 2020-11-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0046_auto_20201104_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot_info',
            name='move_back_error_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lot_info',
            name='move_back_status',
            field=models.IntegerField(default=0),
        ),
    ]
