# Generated by Django 2.1.7 on 2020-12-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdv', '0047_auto_20201113_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot_info',
            name='pellicle_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lot_info',
            name='blank_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
